name: OTT 및 제품 실시간 수집 봇

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 내 깃허브 코드 가져오기
      uses: actions/checkout@v4

    - name: 노드(Node.js) 프로그램 설치
      uses: actions/setup-node@v4
      with:
        node-version: '20' # 👈 오타가 수정된 올바른 옵션 이름입니다!

    - name: 수집 로봇 작동 시작!
      run: node bot.js
